CAPTION = 'AI classes project'

TICK = 5

GAME_DISPLAY_WIDTH = 800
GAME_DISPLAY_HEIGHT = 600
GRID_DISTANCE = 50

assert GAME_DISPLAY_WIDTH % GRID_DISTANCE == 0
assert GAME_DISPLAY_HEIGHT % GRID_DISTANCE == 0

GRID_WIDTH = GAME_DISPLAY_WIDTH / GRID_DISTANCE
GRID_HEIGHT = GAME_DISPLAY_HEIGHT / GRID_DISTANCE

MENU_WIDTH = 200

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
